"""add last name column

Revision ID: 130210d99ff1
Revises: fe163f325a8f
Create Date: 2017-05-18 13:55:37.985691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130210d99ff1'
down_revision = 'fe163f325a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
