"""add first_name column

Revision ID: fe163f325a8f
Revises: 22f891660a0c
Create Date: 2017-05-18 13:48:30.094711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe163f325a8f'
down_revision = '22f891660a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
